#!/bin/bash

# ----MANUAL----
#
# How to use:
#
# syncat -sy				-> To sync files and directorys specified in $HOME/Scripts/syncat/syncat_files.txt
# syncat -a <file>			-> To append file or directory to syncat_files.txt
# syncat -rm <file>			-> To remove file or directory in syncat_files.txt
# syncat -sf <file>			-> To send a single file/directory to server
# syncat -mount <dir> <dest>	-> To mount a directory/filesystem via sshfs to <dest>
# syncat -umount <dir>			-> To unmount a directory
#
#

# IP of current device
# pipe thru xargs to remove trailing whitespaces
HOSTIP=$(ip route get 255.255.255.255 | grep -Po '(?<=src )(\d{1,3}.){4}' | xargs)

PC=""
LAPTOP=""
PC_USER=""
LAPTOP_USER=""

# Used in commands
HOST=""
HOST_USER=""
REMOTE=""
REMOTE_USER=""

function connectViaSSH() {
	ssh "$REMOTE_USER@$REMOTE"
}

function syncFromFile() {
	echo "Sync"
}

function appendToFile() {
	echo "Append"
}

function removeFromFile() {
	echo "Remove"
}

# sendFile <src> <dest>
function sendFile() {
	# Check if <src> is a directory
	if [ -d "$1" ]; then
		scp -r "$1" "$REMOTE_USER@$REMOTE:$2"
	else
		scp "$1" "$REMOTE_USER@$REMOTE:$2"
	fi
}

function mountFS() {
	sshfs "$REMOTE_USER@$REMOTE:$1" "$2"
}

function unmountFS() {
	fusermount3 -u $1
}

function printManual() {
	echo "How to use:"
	echo "syncat -ssh				-> To connect host to remote via ssh"
	echo "syncat -sy				-> To sync files and directorys specified in $HOME/Scripts/syncat/syncat_files.txt"
	echo "syncat -a <file>			-> To append file or directory to syncat_files.txt"
	echo "syncat -rm <file>			-> To remove file or directory in syncat_files.txt"
	echo "syncat -sf <file> <dest>		-> To send a single file/directory to dest on server"
	echo "syncat -mount <dir> <dest>		-> To mount dir on remote to dest on host"
	echo "syncat -umount <dir>			-> To unmount dir from host"
}

# On Laptop
if [ "$HOSTIP" = "$LAPTOP" ]; then
	HOST="$LAPTOP"
	HOST_USER="$LAPTOP_USER"
	REMOTE="$PC"
	REMOTE_USER="$PC_USER"
elif [ "$HOSTIP" = "$PC" ]; then
	HOST="$PC"
	HOST_USER="$PC_USER"
	REMOTE="$LAPTOP"
	REMOTE_USER="$LAPTOP_USER"
else
	echo "wrong host device: x$HOSTIP x"
	echo "Laptop: $LAPTOP"
	echo "PC: $PC"
fi

if [ "$1" = "-ssh" ]; then
	connectViaSSH
elif [ "$1" = "-sy" ]; then
	syncFromFile "Test"
elif [ "$1" = "-a" ]; then
	appendToFile
elif [ "$1" = "-rm" ]; then
	removeFromFile
elif [ "$1" = "-sf" ]; then
	sendFile "$2" $3
elif [ "$1" = "-mount" ]; then
	mountFS "$2" $3
elif [ "$1" = "-umount" ]; then
	unmountFS $2
else
	printManual
fi





