#!/bin/bash

# ----MANUAL----
#
# How to use:
#
# syncat -sy				-> To sync files and directorys specified in $HOME/Scripts/syncat/syncat_files.txt
# syncat -a <file>			-> To append file or directory to syncat_files.txt
# syncat -rm <file>			-> To remove file or directory in syncat_files.txt
# syncat -sf <file>			-> To send a single file/directory to server
# syncat -mount <dir> <dest>	-> To mount a directory/filesystem via sshfs to <dest>
# syncat -umount <dir>			-> To unmount a directory
#
#

# IP of current device
# pipe thru xargs to remove trailing whitespaces
HOSTIP=$(ip route get 255.255.255.255 | grep -Po '(?<=src )(\d{1,3}.){4}' | xargs)

PC="192.168.0.7"
LAPTOP="192.168.0.8"
PC_USER="gooosz"
LAPTOP_USER="rattich"

# Used in commands
HOST=""
HOST_USER=""
REMOTE=""
REMOTE_USER=""



## -- define some constant directories for more convenience
UNI="Uni"
ANIME="/run/media/gooosz/HDD 1TB/Anime/Episodes"

## --

function connectViaSSH() {
	ssh "$REMOTE_USER@$REMOTE" "$@"
}

function syncFromFile() {
	echo "Sync"
}

function appendToFile() {
	echo "Append"
}

function removeFromFile() {
	echo "Remove"
}

# sendFile <src> <dest>
#
# checks prints only files that are missing in the other directory
# diff --brief <absolute path> <absolute path> | sed 's/: /\//' | awk '{print $3}'
function sendFile() {
	src="$1"
	dest="$2"
	# Check if <src> is a directory
	# make sending stuff for Uni faster by typing less
	case $src in
		"uni" | "Uni") src="/home/$HOST_USER/$UNI";;
	esac
	
	case $dest in
		"uni" | "Uni") dest="/home/$REMOTE_USER/$UNI";;
	esac

	if [ -d "$src" ]; then
		scp -r "$src" "$REMOTE_USER@$REMOTE:$dest"
	else
		scp "$src" "$REMOTE_USER@$REMOTE:$dest"
	fi
}

function mountFS() {
	remoteSRC="$1"
	hostDEST="$2"
	# make life more convenient
	case $remoteSRC in
		"uni" | "Uni") remoteSRC="/home/$REMOTE_USER/$UNI";;
		"anime" | "Anime") remoteSRC="$ANIME";;
	esac
	case $hostDEST in
		"uni" | "Uni") hostDEST="/home/$HOST_USER/$UNI";;
		"anime" | "Anime") hostDEST="$(echo ~)/Videos/Anime";;
	esac

	sshfs "$REMOTE_USER@$REMOTE:$remoteSRC" "$hostDEST"
}

function unmountFS() {
	fusermount3 -u $1
}

function printManual() {
	echo "How to use:"
	echo "syncat -ssh				-> To connect host to remote via ssh"
	echo "syncat -sy				-> To sync files and directorys specified in $HOME/Scripts/syncat/syncat_files.txt"
	echo "syncat -a <file>			-> To append file or directory to syncat_files.txt"
	echo "syncat -rm <file>			-> To remove file or directory in syncat_files.txt"
	echo "syncat -sf <file> <dest>		-> To send a single file/directory to dest on server"
	echo "syncat -mount <dir> <dest>		-> To mount dir on remote to dest on host"
	echo "syncat -umount <dir>			-> To unmount dir from host"
}

# On Laptop
if [ "$HOSTIP" = "$LAPTOP" ]; then
	HOST="$LAPTOP"
	HOST_USER="$LAPTOP_USER"
	REMOTE="$PC"
	REMOTE_USER="$PC_USER"
elif [ "$HOSTIP" = "$PC" ]; then
	HOST="$PC"
	HOST_USER="$PC_USER"
	REMOTE="$LAPTOP"
	REMOTE_USER="$LAPTOP_USER"
else
	echo "wrong host device: x$HOSTIP x"
	echo "Laptop: $LAPTOP"
	echo "PC: $PC"
fi

# pass all arguments except the first one to function
case $1 in
	"-ssh")
		connectViaSSH "${@:2}"
		;;
	"-sy")
		syncFromFile "Test"
		;;
	"-rm")
		appendToFile
		;;
	"-sf")
		sendFile "$2" "$3"
		;;
	"-mount")
		mountFS "$2" "$3"
		;;
	"-umount")
		unmountFS $2
		;;
	"-h" | *)
		printManual
		;;
esac


